"""create table_row table

Revision ID: 767296eb645c
Revises: a831fcb56da3
Create Date: 2022-04-14 15:34:09.753591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767296eb645c'
down_revision = 'a831fcb56da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('distance', sa.DECIMAL(precision=7, scale=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_row_date'), 'table_row', ['date'], unique=False)
    op.create_index(op.f('ix_table_row_id'), 'table_row', ['id'], unique=False)
    op.create_index(op.f('ix_table_row_name'), 'table_row', ['name'], unique=False)
    op.create_table('refresh_token',
    sa.Column('body', sa.String(length=63), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expire_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('body')
    )
    op.create_index(op.f('ix_refresh_token_expire_at'), 'refresh_token', ['expire_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_token_expire_at'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_table_row_name'), table_name='table_row')
    op.drop_index(op.f('ix_table_row_id'), table_name='table_row')
    op.drop_index(op.f('ix_table_row_date'), table_name='table_row')
    op.drop_table('table_row')
    # ### end Alembic commands ###
